/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiWhatsappConversationsRouteImport } from './routes/api/whatsapp-conversations'
import { Route as ApiWebsiteChatSessionsRouteImport } from './routes/api/website-chat-sessions'
import { Route as ApiVapiRecordingRouteImport } from './routes/api/vapi-recording'
import { Route as ApiVapiCallsRouteImport } from './routes/api/vapi-calls'
import { Route as ApiTwilioMessagesRouteImport } from './routes/api/twilio-messages'
import { Route as ApiGmailThreadsRouteImport } from './routes/api/gmail-threads'
import { Route as ApiGmailThreadRouteImport } from './routes/api/gmail-thread'
import { Route as ApiGmailFlagRouteImport } from './routes/api/gmail-flag'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppWebsiteRouteImport } from './routes/_app.website'
import { Route as AppSmsRouteImport } from './routes/_app.sms'
import { Route as AppEmailRouteImport } from './routes/_app.email'
import { Route as AppCallsRouteImport } from './routes/_app.calls'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWhatsappConversationsRoute =
  ApiWhatsappConversationsRouteImport.update({
    id: '/api/whatsapp-conversations',
    path: '/api/whatsapp-conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebsiteChatSessionsRoute = ApiWebsiteChatSessionsRouteImport.update({
  id: '/api/website-chat-sessions',
  path: '/api/website-chat-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiRecordingRoute = ApiVapiRecordingRouteImport.update({
  id: '/api/vapi-recording',
  path: '/api/vapi-recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiCallsRoute = ApiVapiCallsRouteImport.update({
  id: '/api/vapi-calls',
  path: '/api/vapi-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioMessagesRoute = ApiTwilioMessagesRouteImport.update({
  id: '/api/twilio-messages',
  path: '/api/twilio-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailThreadsRoute = ApiGmailThreadsRouteImport.update({
  id: '/api/gmail-threads',
  path: '/api/gmail-threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailThreadRoute = ApiGmailThreadRouteImport.update({
  id: '/api/gmail-thread',
  path: '/api/gmail-thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailFlagRoute = ApiGmailFlagRouteImport.update({
  id: '/api/gmail-flag',
  path: '/api/gmail-flag',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppRoute,
} as any)
const AppSmsRoute = AppSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/calls': typeof AppCallsRoute
  '/email': typeof AppEmailRoute
  '/sms': typeof AppSmsRoute
  '/website': typeof AppWebsiteRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/gmail-flag': typeof ApiGmailFlagRoute
  '/api/gmail-thread': typeof ApiGmailThreadRoute
  '/api/gmail-threads': typeof ApiGmailThreadsRoute
  '/api/twilio-messages': typeof ApiTwilioMessagesRoute
  '/api/vapi-calls': typeof ApiVapiCallsRoute
  '/api/vapi-recording': typeof ApiVapiRecordingRoute
  '/api/website-chat-sessions': typeof ApiWebsiteChatSessionsRoute
  '/api/whatsapp-conversations': typeof ApiWhatsappConversationsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calls': typeof AppCallsRoute
  '/email': typeof AppEmailRoute
  '/sms': typeof AppSmsRoute
  '/website': typeof AppWebsiteRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/api/gmail-flag': typeof ApiGmailFlagRoute
  '/api/gmail-thread': typeof ApiGmailThreadRoute
  '/api/gmail-threads': typeof ApiGmailThreadsRoute
  '/api/twilio-messages': typeof ApiTwilioMessagesRoute
  '/api/vapi-calls': typeof ApiVapiCallsRoute
  '/api/vapi-recording': typeof ApiVapiRecordingRoute
  '/api/website-chat-sessions': typeof ApiWebsiteChatSessionsRoute
  '/api/whatsapp-conversations': typeof ApiWhatsappConversationsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/sms': typeof AppSmsRoute
  '/_app/website': typeof AppWebsiteRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/api/gmail-flag': typeof ApiGmailFlagRoute
  '/api/gmail-thread': typeof ApiGmailThreadRoute
  '/api/gmail-threads': typeof ApiGmailThreadsRoute
  '/api/twilio-messages': typeof ApiTwilioMessagesRoute
  '/api/vapi-calls': typeof ApiVapiCallsRoute
  '/api/vapi-recording': typeof ApiVapiRecordingRoute
  '/api/website-chat-sessions': typeof ApiWebsiteChatSessionsRoute
  '/api/whatsapp-conversations': typeof ApiWhatsappConversationsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calls'
    | '/email'
    | '/sms'
    | '/website'
    | '/whatsapp'
    | '/api/gmail-flag'
    | '/api/gmail-thread'
    | '/api/gmail-threads'
    | '/api/twilio-messages'
    | '/api/vapi-calls'
    | '/api/vapi-recording'
    | '/api/website-chat-sessions'
    | '/api/whatsapp-conversations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calls'
    | '/email'
    | '/sms'
    | '/website'
    | '/whatsapp'
    | '/api/gmail-flag'
    | '/api/gmail-thread'
    | '/api/gmail-threads'
    | '/api/twilio-messages'
    | '/api/vapi-calls'
    | '/api/vapi-recording'
    | '/api/website-chat-sessions'
    | '/api/whatsapp-conversations'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/calls'
    | '/_app/email'
    | '/_app/sms'
    | '/_app/website'
    | '/_app/whatsapp'
    | '/api/gmail-flag'
    | '/api/gmail-thread'
    | '/api/gmail-threads'
    | '/api/twilio-messages'
    | '/api/vapi-calls'
    | '/api/vapi-recording'
    | '/api/website-chat-sessions'
    | '/api/whatsapp-conversations'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiGmailFlagRoute: typeof ApiGmailFlagRoute
  ApiGmailThreadRoute: typeof ApiGmailThreadRoute
  ApiGmailThreadsRoute: typeof ApiGmailThreadsRoute
  ApiTwilioMessagesRoute: typeof ApiTwilioMessagesRoute
  ApiVapiCallsRoute: typeof ApiVapiCallsRoute
  ApiVapiRecordingRoute: typeof ApiVapiRecordingRoute
  ApiWebsiteChatSessionsRoute: typeof ApiWebsiteChatSessionsRoute
  ApiWhatsappConversationsRoute: typeof ApiWhatsappConversationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/whatsapp-conversations': {
      id: '/api/whatsapp-conversations'
      path: '/api/whatsapp-conversations'
      fullPath: '/api/whatsapp-conversations'
      preLoaderRoute: typeof ApiWhatsappConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/website-chat-sessions': {
      id: '/api/website-chat-sessions'
      path: '/api/website-chat-sessions'
      fullPath: '/api/website-chat-sessions'
      preLoaderRoute: typeof ApiWebsiteChatSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi-recording': {
      id: '/api/vapi-recording'
      path: '/api/vapi-recording'
      fullPath: '/api/vapi-recording'
      preLoaderRoute: typeof ApiVapiRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi-calls': {
      id: '/api/vapi-calls'
      path: '/api/vapi-calls'
      fullPath: '/api/vapi-calls'
      preLoaderRoute: typeof ApiVapiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio-messages': {
      id: '/api/twilio-messages'
      path: '/api/twilio-messages'
      fullPath: '/api/twilio-messages'
      preLoaderRoute: typeof ApiTwilioMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-threads': {
      id: '/api/gmail-threads'
      path: '/api/gmail-threads'
      fullPath: '/api/gmail-threads'
      preLoaderRoute: typeof ApiGmailThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-thread': {
      id: '/api/gmail-thread'
      path: '/api/gmail-thread'
      fullPath: '/api/gmail-thread'
      preLoaderRoute: typeof ApiGmailThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-flag': {
      id: '/api/gmail-flag'
      path: '/api/gmail-flag'
      fullPath: '/api/gmail-flag'
      preLoaderRoute: typeof ApiGmailFlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website': {
      id: '/_app/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sms': {
      id: '/_app/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof AppSmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCallsRoute: typeof AppCallsRoute
  AppEmailRoute: typeof AppEmailRoute
  AppSmsRoute: typeof AppSmsRoute
  AppWebsiteRoute: typeof AppWebsiteRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallsRoute: AppCallsRoute,
  AppEmailRoute: AppEmailRoute,
  AppSmsRoute: AppSmsRoute,
  AppWebsiteRoute: AppWebsiteRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiGmailFlagRoute: ApiGmailFlagRoute,
  ApiGmailThreadRoute: ApiGmailThreadRoute,
  ApiGmailThreadsRoute: ApiGmailThreadsRoute,
  ApiTwilioMessagesRoute: ApiTwilioMessagesRoute,
  ApiVapiCallsRoute: ApiVapiCallsRoute,
  ApiVapiRecordingRoute: ApiVapiRecordingRoute,
  ApiWebsiteChatSessionsRoute: ApiWebsiteChatSessionsRoute,
  ApiWhatsappConversationsRoute: ApiWhatsappConversationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
